"""Seed demo records for S1 storage baseline."""

from __future__ import annotations

import argparse
import hashlib
import uuid
from datetime import datetime
from pathlib import Path

from opendocs.domain.models import (
    AuditLogModel,
    ChunkModel,
    DocumentModel,
    FileOperationPlanModel,
    KnowledgeItemModel,
    MemoryItemModel,
    RelationEdgeModel,
    SourceRootModel,
)
from opendocs.exceptions import SchemaCompatibilityError
from opendocs.storage.db import build_sqlite_engine, init_db, session_scope
from opendocs.storage.repositories import (
    AuditRepository,
    ChunkRepository,
    DocumentRepository,
    KnowledgeRepository,
    MemoryRepository,
    PlanRepository,
    RelationRepository,
    SourceRepository,
)
from opendocs.utils.path_facts import (
    build_display_path,
    derive_directory_facts,
    derive_source_display_root,
)
from opendocs.utils.time import utcnow_naive

SOURCE_ROOT_ID = "00000000-0000-0000-0000-000000000001"
DOC_ID = "00000000-0000-0000-0000-000000000101"
CHUNK_ID = "00000000-0000-0000-0000-000000000201"
MEMORY_ID = "00000000-0000-0000-0000-000000000301"
PLAN_ID = "00000000-0000-0000-0000-000000000401"
KNOWLEDGE_ID = "00000000-0000-0000-0000-000000000601"
RELATION_EDGE_ID = "00000000-0000-0000-0000-000000000701"
AUDIT_ID = "00000000-0000-0000-0000-000000000501"
DEMO_CHUNK_INDEX = 0
DEMO_MEMORY_SCOPE_ID = "demo-task"
DEMO_MEMORY_KEY = "owner"


def _now() -> datetime:
    return utcnow_naive()


def _preferred_or_new_id(preferred_id: str, exists: bool) -> str:
    if not exists:
        return preferred_id
    return str(uuid.uuid4())


def resolve_seed_paths(db_path: str | Path) -> tuple[str, str, str]:
    base_dir = Path(db_path).resolve().parent
    demo_path = (base_dir / "demo" / "project_overview.md").resolve()
    archive_path = (base_dir / "archive" / "project_overview.md").resolve()
    relative_path = demo_path.name
    return str(demo_path), relative_path, str(archive_path)


def _ensure_demo_document(demo_doc_path: str) -> None:
    demo_path = Path(demo_doc_path)
    demo_path.parent.mkdir(parents=True, exist_ok=True)
    if not demo_path.exists():
        demo_path.write_text(
            "# Project Overview\n\n"
            "This file is generated by seed_demo_data.py for S1 baseline tests.\n",
            encoding="utf-8",
        )


def seed_demo_data(db_path: str | Path) -> dict[str, int]:
    resolved_db_path = Path(db_path)
    demo_doc_path, demo_doc_relative_path, demo_archive_path = resolve_seed_paths(resolved_db_path)
    demo_source_root_path = str(Path(demo_doc_path).resolve().parent)
    _ensure_demo_document(demo_doc_path)
    demo_doc_size = Path(demo_doc_path).stat().st_size
    init_db(resolved_db_path)
    engine = build_sqlite_engine(resolved_db_path)
    inserted = {
        "documents": 0,
        "chunks": 0,
        "knowledge_items": 0,
        "relation_edges": 0,
        "memory_items": 0,
        "file_operation_plans": 0,
        "audit_logs": 0,
    }

    try:
        with session_scope(engine) as session:
            document_repo = DocumentRepository(session)
            chunk_repo = ChunkRepository(session)
            memory_repo = MemoryRepository(session)
            plan_repo = PlanRepository(session)
            audit_repo = AuditRepository(session)
            source_repo = SourceRepository(session)

            now = _now()
            source_root = source_repo.get_by_path(demo_source_root_path)
            if source_root is None:
                preferred_source_root_id = (
                    SOURCE_ROOT_ID
                    if source_repo.get_by_id(SOURCE_ROOT_ID) is None
                    else str(uuid.uuid4())
                )
                source_root = source_repo.create(
                    SourceRootModel(
                        source_root_id=preferred_source_root_id,
                        path=demo_source_root_path,
                        display_root=derive_source_display_root(
                            demo_source_root_path,
                            source_root_id=preferred_source_root_id,
                        ),
                        label="Seed Demo Source",
                        exclude_rules_json={},
                        recursive=True,
                        is_active=True,
                        created_at=now,
                        updated_at=now,
                    )
                )

            document = document_repo.get_by_path(demo_doc_path)
            if document is None:
                document_id = _preferred_or_new_id(
                    DOC_ID,
                    document_repo.get_by_id(DOC_ID) is not None,
                )
                directory_path, relative_directory_path = derive_directory_facts(
                    demo_doc_path,
                    demo_doc_relative_path,
                )
                document_repo.create(
                    DocumentModel(
                        doc_id=document_id,
                        path=demo_doc_path,
                        relative_path=demo_doc_relative_path,
                        display_path=build_display_path(
                            source_root.display_root,
                            demo_doc_relative_path,
                        ),
                        directory_path=directory_path,
                        relative_directory_path=relative_directory_path,
                        source_root_id=source_root.source_root_id,
                        source_path=demo_doc_path,
                        hash_sha256=hashlib.sha256(Path(demo_doc_path).read_bytes()).hexdigest(),
                        title="Project Overview",
                        file_type="md",
                        size_bytes=demo_doc_size,
                        created_at=now,
                        modified_at=now,
                        indexed_at=now,
                        parse_status="success",
                        category="project",
                        tags_json=["demo", "overview"],
                        sensitivity="internal",
                        is_deleted_from_fs=False,
                    )
                )
                inserted["documents"] += 1
                document = document_repo.get_by_id(document_id)

            if document is None:
                raise RuntimeError("failed to resolve demo document")

            chunk = chunk_repo.get_by_document_index(document.doc_id, DEMO_CHUNK_INDEX)
            if chunk is None:
                chunk_id = _preferred_or_new_id(
                    CHUNK_ID,
                    chunk_repo.get_by_id(CHUNK_ID) is not None,
                )
                demo_chunk_text = "OpenDocs demo chunk text for retrieval and audit tracing."
                chunk_repo.create(
                    ChunkModel(
                        chunk_id=chunk_id,
                        doc_id=document.doc_id,
                        chunk_index=DEMO_CHUNK_INDEX,
                        text=demo_chunk_text,
                        char_start=0,
                        char_end=len(demo_chunk_text),
                        page_no=None,
                        paragraph_start=0,
                        paragraph_end=0,
                        heading_path="Overview",
                        token_estimate=16,
                        embedding_model="demo-embedding-model",
                        embedding_key="chunk-demo-0001",
                    )
                )
                inserted["chunks"] += 1
                chunk = chunk_repo.get_by_id(chunk_id)

            if chunk is None:
                raise RuntimeError("failed to resolve demo chunk")

            knowledge_repo = KnowledgeRepository(session)
            relation_repo = RelationRepository(session)

            if knowledge_repo.get_by_id(KNOWLEDGE_ID) is None:
                knowledge_repo.create(
                    KnowledgeItemModel(
                        knowledge_id=KNOWLEDGE_ID,
                        doc_id=document.doc_id,
                        chunk_id=chunk.chunk_id,
                        summary="OpenDocs is a local-first AI document management system.",
                        entities_json=["OpenDocs"],
                        topics_json=["document-management", "local-first"],
                        confidence=0.9,
                    )
                )
                inserted["knowledge_items"] += 1

            if relation_repo.get_by_id(RELATION_EDGE_ID) is None:
                relation_repo.create(
                    RelationEdgeModel(
                        edge_id=RELATION_EDGE_ID,
                        src_type="document",
                        src_id=document.doc_id,
                        dst_type="chunk",
                        dst_id=chunk.chunk_id,
                        relation_type="mentions",
                        weight=1.0,
                        evidence_chunk_id=chunk.chunk_id,
                    )
                )
                inserted["relation_edges"] += 1

            memory = memory_repo.get_by_scope_key(
                memory_type="M1",
                scope_type="task",
                scope_id=DEMO_MEMORY_SCOPE_ID,
                key=DEMO_MEMORY_KEY,
            )
            if memory is None:
                memory_id = _preferred_or_new_id(
                    MEMORY_ID,
                    memory_repo.get_by_id(MEMORY_ID) is not None,
                )
                memory_repo.create(
                    MemoryItemModel(
                        memory_id=memory_id,
                        memory_type="M1",
                        scope_type="task",
                        scope_id=DEMO_MEMORY_SCOPE_ID,
                        key=DEMO_MEMORY_KEY,
                        content="Alice",
                        importance=0.8,
                        status="active",
                        ttl_days=30,
                        confirmed_count=1,
                        last_confirmed_at=now,
                        updated_at=now,
                    )
                )
                inserted["memory_items"] += 1

            if plan_repo.get_by_id(PLAN_ID) is None:
                plan_repo.create(
                    FileOperationPlanModel(
                        plan_id=PLAN_ID,
                        operation_type="move",
                        status="draft",
                        item_count=1,
                        risk_level="low",
                        preview_json={
                            "items": [
                                {
                                    "source": demo_doc_path,
                                    "target": demo_archive_path,
                                }
                            ]
                        },
                    )
                )
                inserted["file_operation_plans"] += 1

            if audit_repo.get_by_id(AUDIT_ID) is None:
                audit_repo.create(
                    AuditLogModel(
                        audit_id=AUDIT_ID,
                        timestamp=now,
                        actor="system",
                        operation="seed_demo_data",
                        target_type="document",
                        target_id=document.doc_id,
                        result="success",
                        detail_json={
                            "file_path": demo_doc_path,
                            "chunk_id": chunk.chunk_id,
                            "note": "seed for S1 tests",
                        },
                        trace_id="trace-seed-001",
                    )
                )
                inserted["audit_logs"] += 1
    finally:
        engine.dispose()

    return inserted


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Seed OpenDocs demo data")
    parser.add_argument(
        "--db-path",
        required=True,
        type=Path,
        help="SQLite database path",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        inserted = seed_demo_data(args.db_path)
    except SchemaCompatibilityError as exc:
        print(f"schema error: {exc}")
        return 2
    print(f"seed completed for {args.db_path}: {inserted}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
